# Start programming with R

# Working Directory

In [20]:
getwd() #to get the path of working directory

[1] "/Users/annagromyko"

In [21]:
list.files() #all files in working directory

[1] "_vector_operations.zip"              "Analitics-"                         
 [3] "Applications"                        "Basis_R.ipynb"                      
 [5] "Covid_19_Project"                    "DA with R.ipynb"                    
 [7] "Data Analysis Workflow"              "Data science Coursera.ipynb"        
 [9] "Desktop"                             "Documents"                          
[11] "Downloads"                           "generate_password"                  
[13] "Library"                             "magic ball"                         
[15] "matrix_operations-.ipynb"            "Movies"                             
[17] "Music"                               "Open ML course"                     
[19] "Pictures"                            "Public"                             
[21] "PycharmProjects"                     "Python_projects"                    
[23] "sentences.txt"                       "Untitled Folder"                    
[25] "Untitled Folder 1"                   "untitled-1.py"                      
[27] "untitled-2.py"                       "untitled-3.py"                      
[29] "untitled-5.py"                       "untitled-6.py"                      
[31] "untitled-7.py"                       "untitled-8.py"                      
[33] "Untitled.ipynb"                      "Untitled1.ipynb"                    
[35] "Untitled2.ipynb"                     "Untitled3.ipynb"                    
[37] "vector_operations.ipynb"             "Yandex.Disk-annkka3.localized"      
[39] "Yandex.Disk-KanichevVadim.localized" "Yandex.Disk.localized"              
[41] "Без названия.ipynb"                  "Без названия1.ipynb"                
[43] "Без названия2.ipynb"                 "Без названия3.ipynb"                
[45] "Без названия4.ipynb"                 "Без названия5.ipynb"                
[47] "задание 2 неделя.ipynb"              "предел.py"                          
[49] "Угадай число.py"                     "функция 2 неделя.ipynb"

In [22]:
list.dirs("..", recursive=F)

[1] "../annagromyko" "../Shared"

## Vector

In [1]:
v1 <- c(5:10)
v1

[1]  5  6  7  8  9 10

In [11]:
v2 <- seq(2,8, by=0.25)
v2

[1] 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 5.25 5.50
[16] 5.75 6.00 6.25 6.50 6.75 7.00 7.25 7.50 7.75 8.00

In [12]:
v3 <- seq(2,10, length=5)
v3

[1]  2  4  6  8 10

In [14]:
v4 <- rep(1:3, times = 3)
v4

[1] 1 2 3 1 2 3 1 2 3

In [15]:
v5 <- rep(1:3, each = 4)
v5

[1] 1 1 1 1 2 2 2 2 3 3 3 3

In [17]:
v6 <- rep(1:3, length = 5)
v6

[1] 1 2 3 1 2

In [18]:
all.equal(1, 1, 1, 1,1) 
#combines all values

[1] TRUE

In [20]:
v7 <- c(1, 2, 3, 2, 3, 2, 4, 3, 5)

unique(v7) #returns vector with unique values

[1] 1 2 3 4 5

In [22]:
sort(v2,  decreasing = T) #sorts values in vector

[1] 8.00 7.75 7.50 7.25 7.00 6.75 6.50 6.25 6.00 5.75 5.50 5.25 5.00 4.75 4.50
[16] 4.25 4.00 3.75 3.50 3.25 3.00 2.75 2.50 2.25 2.00

In [23]:
typeof(v7) #to recognize the type

[1] "double"

In [24]:
#is.* instead of * we should type the type of needed
#is.character
#is.logical
#is.numeric

is.numeric(v7)

[1] TRUE

In [25]:
#as.* if we want to convert to type

as.character(v7)

[1] "1" "2" "3" "2" "3" "2" "4" "3" "5"

In [27]:
length(v7) #to find the length of vector

[1] 9

In [28]:
names(v7) <- c('one', 'two', 'three') #to name variables

In [29]:
v7

one   two three  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
    1     2     3     2     3     2     4     3     5

In [31]:
floor(v2) #to round the number
# v2 <- 2 2.25 2.5 2.75 3 3.25 3.5 3.75 4 4.25 4.5 4.75 5 5.25 5.5 5.75 6 6.25 6.5 6.75 7 7.25 7.5 7.75 8

[1] 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6 7 7 7 7 8

## IF , ELSE

In [39]:
# runif(n) - n independent experiments of random value from 0 to 1

ifelse(runif(8) > 0.5, 'Heads', "Tails")


[1] "Heads" "Heads" "Tails" "Tails" "Heads" "Tails" "Heads" "Heads"

In [44]:
x <- runif(8)

ifelse( x < 1/3, 'Stone',
      ifelse (x < 2/3, 'Scissors', 'Paper'))

[1] "Stone"    "Paper"    "Scissors" "Paper"    "Scissors" "Scissors" "Paper"   
[8] "Stone"

## Multilpy choise

In [45]:
switch ('factorial', 
       sum = 5+5,
       product = 5*5,
       factorial = factorial(5), 
       0)

[1] 120

# Cycles

## REPEAT

In [47]:
i <- 0
repeat{
    i <- i + runif(1)
    print(i)
    if (i>5) break  
}

[1] 0.03962049
[1] 0.1117227
[1] 0.386933
[1] 1.316263
[1] 2.262219
[1] 2.792907
[1] 3.247193
[1] 4.172839
[1] 4.834981
[1] 4.842735
[1] 5.550335


## WHILE

In [49]:
i <- 2^14
while (i>1000){
    i <- i/2
    print(i)     
}

[1] 8192
[1] 4096
[1] 2048
[1] 1024
[1] 512


## FOR

In [50]:
for (i in 1:8) {
    if (i %% 2 == 0) print(i)
}

[1] 2
[1] 4
[1] 6
[1] 8


In [52]:
for (i in letters) {
    if (i  == 'b') next
    if (i == 'd') break
    print(i)
}

[1] "a"
[1] "c"


## Random integers 

In [62]:
round(runif(n= 10 , min= 1 , max= 6 ), 0)

[1] 4 6 5 6 4 4 4 5 4 3

In [63]:
dice_roll <- function(n) {
  return (sample(x = 1:6, size = n, replace = TRUE))
}


In [64]:
dice_roll(10)

[1] 1 4 1 6 1 5 2 1 2 4

# Recycling Vectors

In [2]:
1:5 + 0:1


Warning message in 1:5 + 0:1:
“longer object length is not a multiple of shorter object length”

[1] 1 3 3 5 5

In [74]:
v <- c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)

## Indexing

In [76]:
v[c(1, 4:6, 8)]

[1] 10 40 50 60 80

In [77]:
v[-5] #all except 5

[1]  10  20  30  40  60  70  80  90 100

In [79]:
v[c(-1, -(4:7), -length(v))]

[1] 20 30 80 90

In [80]:
v[rep(c(T, F), 5)]

[1] 10 30 50 70 90

In [81]:
v[c(F, T)]

[1]  20  40  60  80 100

In [83]:
v[v>77 & v<99]

[1] 80 90

In [84]:
#If we have named vector we can use name as indexing

v1 <- c('one'=1, 'two'=2, 'three'=3, 'four'=4, 'five'=5)

In [87]:
v1[c('two', 'five')]

two five 
   2    5

# Functions ALL and ANY

In [89]:
all(v1 < 100); all(v1>2)

[1] TRUE

[1] FALSE

In [91]:
any(v1 > 100); any(v1>2)

[1] FALSE

[1] TRUE

# WHICH

In [93]:
#we recieve indexes

which(v>50)

[1]  6  7  8  9 10

In [94]:
#indexes of max and min value

which.max(v); which.min(v)

[1] 10

[1] 1

# Attributes

In [95]:
x = c(5, 3, 9)
names(x) <- c('V', 'III', 'IX')

In [97]:
attr(x, 'author') <- 'Caesar'
attributes(x)

$names
[1] "V"   "III" "IX" 

$author
[1] "Caesar"

In [99]:
attributes(x) <- NULL #to delete all atributes

attributes(x)

NULL

In [103]:
#FIZZ BUZZ 

x <- 1:100
z <- 1:100
z[x %% 5 == 0] <- 'buzz'
z[x %% 3 == 0] <- 'fizz'
z[x %% 15 == 0] <- 'fizz buzz'
z

[1] "1"         "2"         "fizz"      "4"         "buzz"      "fizz"     
  [7] "7"         "8"         "fizz"      "buzz"      "11"        "fizz"     
 [13] "13"        "14"        "fizz buzz" "16"        "17"        "fizz"     
 [19] "19"        "buzz"      "fizz"      "22"        "23"        "fizz"     
 [25] "buzz"      "26"        "fizz"      "28"        "29"        "fizz buzz"
 [31] "31"        "32"        "fizz"      "34"        "buzz"      "fizz"     
 [37] "37"        "38"        "fizz"      "buzz"      "41"        "fizz"     
 [43] "43"        "44"        "fizz buzz" "46"        "47"        "fizz"     
 [49] "49"        "buzz"      "fizz"      "52"        "53"        "fizz"     
 [55] "buzz"      "56"        "fizz"      "58"        "59"        "fizz buzz"
 [61] "61"        "62"        "fizz"      "64"        "buzz"      "fizz"     
 [67] "67"        "68"        "fizz"      "buzz"      "71"        "fizz"     
 [73] "73"        "74"        "fizz buzz" "76"        "77"        "fizz"     
 [79] "79"        "buzz"      "fizz"      "82"        "83"        "fizz"     
 [85] "buzz"      "86"        "fizz"      "88"        "89"        "fizz buzz"
 [91] "91"        "92"        "fizz"      "94"        "buzz"      "fizz"     
 [97] "97"        "98"        "fizz"      "buzz"

In [109]:
set.seed(42)
# Neighbours with greatest diff

x <- sample(1:100, 50)
x

[1]  49  65  25  74  18 100  47  24  71  89  37  20  26   3  41  27  36   5  34
[20]  87  58  42  93  30  43  15  22  80   8  84  68  96   4  50  95  88  67   6
[39]  63   2  52  81  54  21  61  55  38  10  40  83

In [112]:
x[-1]
x[-length(x)]
x[-1] - x[-length(x)]

[1]  65  25  74  18 100  47  24  71  89  37  20  26   3  41  27  36   5  34  87
[20]  58  42  93  30  43  15  22  80   8  84  68  96   4  50  95  88  67   6  63
[39]   2  52  81  54  21  61  55  38  10  40  83

[1]  49  65  25  74  18 100  47  24  71  89  37  20  26   3  41  27  36   5  34
[20]  87  58  42  93  30  43  15  22  80   8  84  68  96   4  50  95  88  67   6
[39]  63   2  52  81  54  21  61  55  38  10  40

[1]  16 -40  49 -56  82 -53 -23  47  18 -52 -17   6 -23  38 -14   9 -31  29  53
[20] -29 -16  51 -63  13 -28   7  58 -72  76 -16  28 -92  46  45  -7 -21 -61  57
[39] -61  50  29 -27 -33  40  -6 -17 -28  30  43

In [118]:
k <- which.max(abs(x[-1] - x[-length(x)]))
k
max_neighs <- x[c(k, k+1)]
max_neighs

[1] 32

[1] 96  4

In [120]:
#Multiply min/max

x <- sample(1:100, 50, replace= T)
x

[1] 55 16 90 43 42 42 97 57 29 25 63 32 81 14  6 47 43 62 37 80 31 34 94 96  6
[26] 86 38 95  6 84 15 34 42 87 60 12 26 41 65 66 56 24 98 25 92 61 62 14 34 66

In [125]:
min(x)
which.min(x)
which(x == min(x)) #all indexes with min value

[1] 6

[1] 15

[1] 15 25 29

In [126]:
x=c(0, 0, 3, 4, 4, 8)

x[-1] - x[-length(x)]

[1] 0 3 1 0 4

In [127]:
is_monotone <- function(x) {
 diff <- x[-1] - x[-length(x)]
 if (all(diff >= 0) | all(diff<= 0)) {
     return (T) } else return (F)    
}


In [130]:
is_monotone(v)

[1] TRUE

In [129]:
v <-  rep(0, 10)
v

[1] 0 0 0 0 0 0 0 0 0 0

In [131]:
factorial(5)

[1] 120

# Matrix

In [132]:
matrix(1:6, nrow=2, ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [133]:
matrix(1:6, nrow=2, ncol=3, byrow=T)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [136]:
m <- matrix(1:6, nrow=2, ncol=3, byrow=T)
dim(m) #sizes of our matrix
c(nrow(m), ncol(m))

[1] 2 3

[1] 2 3

In [138]:
m1 <- matrix(1:6, nrow=2)
m2 <- matrix(1:6, nrow=2)
m3 <- matrix(1:6, ncol=2)
#Matrix mulpiplication

#simple multiplication 
m1*m2

#matrix multiplication
m1 %*% m3


[,1] [,2] [,3]
[1,] 1     9   25  
[2,] 4    16   36

[,1] [,2]
[1,] 22   49  
[2,] 28   64

## Indexing of Matrix

In [140]:
m <- matrix(1:10, ncol=5)
m
m[1,3]
m[2,]
m[,4]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[1] 5

[1]  2  4  6  8 10

[1] 7 8

In [141]:
ind <- 3
m[, ind] #returns vector
m[, ind, drop=F] #returns matrix

[1] 5 6

[,1]
[1,] 5   
[2,] 6

In [143]:
rownames(m) <- c('row1', 'row2')
colnames(m) <- paste0('column', 1:5)
m

column1 column2 column3 column4 column5
row1 1       3       5       7        9     
row2 2       4       6       8       10

# Function APPLY

In [151]:
m <- matrix(1:30, 5)
m

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     6   11   16   21   26  
[2,] 2     7   12   17   22   27  
[3,] 3     8   13   18   23   28  
[4,] 4     9   14   19   24   29  
[5,] 5    10   15   20   25   30

In [146]:
f <- function(x) sum(x^2)

In [153]:
apply(m, 1, f) #apply function to rows (returns vector)
apply(m, 2, f) #apply function to columns


[1] 1531 1699 1879 2071 2275

[1]   55  330  855 1630 2655 3930

In [155]:
apply(m, 1:2, function(x) if (x>13) x else 13) #apply function to every value of matrix

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 13   13   13   16   21   26  
[2,] 13   13   13   17   22   27  
[3,] 13   13   13   18   23   28  
[4,] 13   13   14   19   24   29  
[5,] 13   13   15   20   25   30

# rowSums, colSums, rowMeans, colMeans

In [157]:
rowSums(m) #sums rows
colSums(m) #sums columns
rowMeans(m) #calculate row mean
colMeans(m) #calculate column mean

[1]  81  87  93  99 105

[1]  15  40  65  90 115 140

[1] 13.5 14.5 15.5 16.5 17.5

[1]  3  8 13 18 23 28

In [177]:
# finction to join 2 matrix by their diagonal
bind_diag <- function(m1, m2, fill) {
    m3 <- matrix(fill, 
                 nrow = nrow(m1) + nrow(m2),
                 ncol = ncol(m1) + ncol(m2))
    m3[1:nrow(m1), 1:ncol(m1)] <- m1
    m3[nrow(m1)+1: nrow(m2), ncol(m1)+1: ncol(m2)] <- m2
    return (m3)
    }


In [178]:
m1 <- matrix(1:12, nrow=3)
m2 <- matrix(10:15, ncol=3)

In [179]:
bind_diag(m1, m2, fill=NA)

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]  1    4    7   10   NA   NA   NA  
[2,]  2    5    8   11   NA   NA   NA  
[3,]  3    6    9   12   NA   NA   NA  
[4,] NA   NA   NA   NA   10   12   14  
[5,] NA   NA   NA   NA   11   13   15

In [196]:
build_ziggurat <- function(n) {
    m <- matrix(1, nrow=n*2-1, ncol=n*2-1)
    m[n,n] <- n
    for (i in 0:(n-1)) {
        m[n-i,] <- n-i
        m[,n-i] <- n-i
        m[n+i,] <- n-i
        m[,n+i] <- n-i
    }
    return(m)
}


build_ziggurat <- function(n) {
    m <- matrix(c(1:n,(n-1):1), 2*n-1, 2*n-1)
pmin(m,t(m))
}


In [197]:
build_ziggurat(5)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,] 1    1    1    1    1    1    1    1    1   
 [2,] 1    2    2    2    2    2    2    2    1   
 [3,] 1    2    3    3    3    3    3    2    1   
 [4,] 1    2    3    4    4    4    3    2    1   
 [5,] 1    2    3    4    5    4    3    2    1   
 [6,] 1    2    3    4    4    4    3    2    1   
 [7,] 1    2    3    3    3    3    3    2    1   
 [8,] 1    2    2    2    2    2    2    2    1   
 [9,] 1    1    1    1    1    1    1    1    1

# List

In [198]:
list(1:5, 'mydata', matrix(1:10, ncol=2))

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] "mydata"

[[3]]
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

In [199]:
list(a=1:5, b='mydata', c=matrix(1:10, ncol=2), d=c('a', 'b', 'c'))

$a
[1] 1 2 3 4 5

$b
[1] "mydata"

$c
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

$d
[1] "a" "b" "c"

# Vector & List Conversion

In [201]:
v = 1:9 
list(v) #converts vector to list

[[1]]
[1] 1 2 3 4 5 6 7 8 9

In [213]:
l <- list(1:3, c(4,5), last=6)
l


[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

$last
[1] 6

In [214]:
unlist(l)
typeof(unlist(l))

last 
   1    2    3    4    5    6

[1] "double"

In [ ]:
#Indexing

In [211]:
l[1:2] #sublist by index, returns list

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

In [224]:
l[-(2:3)] #returns list

[[1]]
[1] 1 2 3

In [216]:
l$last #returns vector

[1] 6

In [226]:
l[c(T,F,T)] #returns list
l['last'] #returns list

[[1]]
[1] 1 2 3

$last
[1] 6

$last
[1] 6

In [221]:
#Indexing for element

l[[1]] #returns vector 

[1] 1 2 3

In [227]:
l[['last']] #returns vector 

[1] 6

In [228]:
#Deleting elements from list

l[[3]] <- NULL
l

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

In [230]:
l[[4]] <- 99
l

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

[[3]]
NULL

[[4]]
[1] 99

# Functions LAPPLY and SAPPLY

In [232]:
lapply(l, length) #returns length of each element in list

[[1]]
[1] 3

[[2]]
[1] 2

[[3]]
[1] 0

[[4]]
[1] 1

In [233]:
lapply(l, paste, collapse= '/')

[[1]]
[1] "1/2/3"

[[2]]
[1] "4/5"

[[3]]
[1] ""

[[4]]
[1] "99"

In [235]:
sapply(l, paste, collapse= '/') #returns vector where it's possible (simplify apply)

"1/2/3"   "4/5"      ""    "99"

## DIAG

In [236]:
m <- matrix(1:25, nrow=5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [242]:
diag(m) #returns vector from main diagonal of matrix

[1]  1  7 13 19 25

In [243]:
diag(5) #returns matrix of n size with 1 on main diag

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

In [244]:
diag(3, 5) #returns matrix of m size with n on main diag

[,1] [,2] [,3] [,4] [,5]
[1,] 3    0    0    0    0   
[2,] 0    3    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    3    0   
[5,] 0    0    0    0    3

In [269]:
#Function counting elements of vector, returns matrix of unique elements with their freq

count_elements <- function(x) {
    unique <- sort(unique(x))
    count <- sapply(unique, function(i) length(x[x == i]))
    return(rbind(unique, count))
}


In [270]:
x <- c(5, 2, 7, 7, 7, 2, 0, 0)

In [271]:
count_elements(x)

[,1] [,2] [,3] [,4]
unique 0    2    5    7   
count  2    2    1    3


# DATAFRAME

In [283]:
df <- data.frame(x=1:4, y=letters[1:4], z=c(T, F))
df

x y z    
1 1 a  TRUE
2 2 b FALSE
3 3 c  TRUE
4 4 d FALSE

In [285]:
str(df) #info about df

'data.frame':	4 obs. of  3 variables:
 $ x: int  1 2 3 4
 $ y: Factor w/ 4 levels "a","b","c","d": 1 2 3 4
 $ z: logi  TRUE FALSE TRUE FALSE


In [287]:
rownames(df) <- c('Alpha', 'Bravo', 'Charlie', 'Delta') #same names(df)

In [288]:
df

x y z    
Alpha   1 a  TRUE
Bravo   2 b FALSE
Charlie 3 c  TRUE
Delta   4 d FALSE

In [289]:
dim(df) #sizes of df

[1] 4 3

In [290]:
nrow(df); ncol(df) #number of rows and number of columns

#length(df) == ncol(df)

[1] 4

[1] 3

# Indexing in DataFrame

In [291]:
df[3:4, -1]

y z    
Charlie c  TRUE
Delta   d FALSE

In [293]:
df[c(F, T), c('z', 'x')]

z     x
Bravo FALSE 2
Delta FALSE 4

In [295]:
df[,1]; df [,1, drop=F]

[1] 1 2 3 4

x
Alpha   1
Bravo   2
Charlie 3
Delta   4

In [297]:
df$z; df[[3]]; df[['z']]

[1]  TRUE FALSE  TRUE FALSE

[1]  TRUE FALSE  TRUE FALSE

[1]  TRUE FALSE  TRUE FALSE

## Conditioning Filtering

In [299]:
df[df$x > 2, ]

x y z    
Charlie 3 c  TRUE
Delta   4 d FALSE

In [300]:
subset(df, x>2)

x y z    
Charlie 3 c  TRUE
Delta   4 d FALSE

In [301]:
subset(df, x>2, select=c(x,z))

x z    
Charlie 3  TRUE
Delta   4 FALSE

## Combinig dataframes

In [302]:
cbind(df, df)

x y z     x y z    
Alpha   1 a  TRUE 1 a  TRUE
Bravo   2 b FALSE 2 b FALSE
Charlie 3 c  TRUE 3 c  TRUE
Delta   4 d FALSE 4 d FALSE

In [304]:
rbind(df, df)

x y z    
Alpha    1 a  TRUE
Bravo    2 b FALSE
Charlie  3 c  TRUE
Delta    4 d FALSE
Alpha1   1 a  TRUE
Bravo1   2 b FALSE
Charlie1 3 c  TRUE
Delta1   4 d FALSE

In [306]:
df_salary <- data.frame(x=c(3,2,6,1), salary=c(100, 200, 300, 100))
merge(df, df_salary, by='x') #inner join of two dataframes

x y z     salary
1 1 a  TRUE 100   
2 2 b FALSE 200   
3 3 c  TRUE 100

In [307]:
data <- attitude

In [329]:

#Our goal is to find a company from attitude DataFrame which learning rate is in top 5 companies 
#and sum of (complaints, raises  and  advance) columns is max


top_learning <- sort(data$learning, decreasing=T)[5]
top_learning_data <- subset(data, learning >= top_learning)
rating <- apply(top_learning_data, 1, function(x) x[2] + x[7] + x[5])
max_rating <- max(rating)
ind <- which(rating == max_rating)
top_learning_data[ind,]

rating complaints privileges learning raises critical advance
29 85     85         71         71       77     74       55

In [ ]:
# Our goal is to choose all columns from dataset attitude except rating, where rating is less then 50

subset(sel = -rating, sub = rating < 50, attitude)
subset(attitude, rating < 50, -rating)
attitude[attitude$rating < 50, names(attitude) != "rating"]

# Importing and inspecting Data

In [348]:
summary(df)

       x        y         z          
 Min.   :1.00   a:1   Mode :logical  
 1st Qu.:1.75   b:1   FALSE:2        
 Median :2.50   c:1   TRUE :2        
 Mean   :2.50   d:1                  
 3rd Qu.:3.25                        
 Max.   :4.00                        

In [120]:
df1 <- read.csv('https://raw.githubusercontent.com/tonytonov/Rcourse/master/R%20programming/avianHabitat.csv')
df2 <- read.csv('https://raw.githubusercontent.com/tonytonov/Rcourse/master/R%20programming/avianHabitat2.csv')

In [108]:
head(df1, 4)
head(df2, 6)

#As we can see our data2 has some rows that we don't need, so we need to skip them

Site         Observer Subpoint VOR PDB DBHt PW WHt PE EHt PA AHt PH HHt PL
1 BunkerHill27 RA       1        6.0 3   5.2  0  0.0 4  2.9 0  0   4  3.0 0 
2 BunkerHill27 RA       2        4.5 2   3.1  3  4.7 3  4.1 0  0   3  3.5 2 
3 BunkerHill27 RA       3        2.0 4   5.5  1  5.8 3  3.9 0  0   3  7.5 0 
4 BunkerHill27 RA       4        2.5 3   6.2  0  0.0 3  4.0 0  0   4  5.0 0 
  LHt PB
1 0   0 
2 1   0 
3 0   0 
4 0   0

Dear.Sir.or.Madam                                                                                                           
1 Here's the rest of our data                                                                                                 
2 With best regards                                                                                                           
3 Carlos Linayas                                                                                                              
4 ----data starts from here!----                                                                                              
5 Site;Subpoint;VOR;PDB;DBHt;PW;WHt;PE;EHt;PA;AHt;PH;HHt;PL;LHt;PB % I removed Observer column since all measurements are mine
6 HortonCreek111;1;3;0;0;0;0;4;3.5;0;0;3;5;0;0;0                                                                              
  X                    
1  sorry for the delay!
2                      
3                      
4                      
5                      
6

In [109]:
df2 <- read.csv(sep = ";", skip = 5, header = T, comment.char = "%", quote = "", na.strings = "Don't remember", file = 'https://raw.githubusercontent.com/tonytonov/Rcourse/master/R%20programming/avianHabitat2.csv')

In [110]:
head(df2, 6) 
#We can see that data2 don't have column Observer, so we need to remove it in the first dataset before merging them

Site           Subpoint VOR PDB DBHt PW WHt  PE EHt PA AHt PH HHt PL LHt PB
1 HortonCreek111 1        3.0 0   0.0  0   0.0 4  3.5 0  0   3  5.0 0  0.0 0 
2 HortonCreek111 2        3.0 0   0.0  4  18.5 0  0.0 0  0   4  5.7 0  0.0 0 
3 HortonCreek111 3        2.0 0   0.0  3  11.3 2  3.0 0  0   4  4.9 1  0.2 0 
4 HortonCreek111 4        3.5 0   0.0  4  15.8 0  0.0 0  0   3  4.2 0  0.0 0 
5 HortonCreek111 5        0.0 1   0.3  2   0.5 4  0.4 0  0   2  1.4 5  0.3 0 
6 HortonCreek111 6        0.0 2   0.7  3   0.5 4  0.5 0  0   1  1.6 3  0.5 1

In [111]:
df1 <- df1[,-2]
head(df1)

Site         Subpoint VOR PDB DBHt PW WHt PE EHt PA AHt PH HHt PL LHt PB
1 BunkerHill27 1        6.0 3   5.2  0  0.0 4  2.9 0  0   4  3.0 0  0   0 
2 BunkerHill27 2        4.5 2   3.1  3  4.7 3  4.1 0  0   3  3.5 2  1   0 
3 BunkerHill27 3        2.0 4   5.5  1  5.8 3  3.9 0  0   3  7.5 0  0   0 
4 BunkerHill27 4        2.5 3   6.2  0  0.0 3  4.0 0  0   4  5.0 0  0   0 
5 BunkerHill27 5        4.0 4   5.4  0  0.0 3  3.5 0  0   4  3.7 0  0   0 
6 BunkerHill27 6        2.0 3   4.0  0  0.0 3  4.1 0  0   2  3.5 0  0   0

In [112]:
#check that we have same sizes for columns and check number of rows before joining
dim(df1)
dim(df2) 

[1] 1070   16

[1] 18 16

In [113]:
df3 <- rbind(df1, df2)
dim(df3) #1070+18 == 1088 

[1] 1088   16

In [114]:
#Our goal if to find the mean percent of covering, at first we should find the columns with percent values
# then we will sum all the values and save it to percent_covering column

p_cols <- names(df3)[-c(1:3)][c(T, F)] 
df3$percent_covering <- rowSums(df3[p_cols])


In [115]:
mean(df3$percent_covering)

[1] 9.571691

In [116]:
# Our next goal is to find the maximum value in each column containing HT in name


ht_cols <- names(df3)[-c(1:4, ncol(df3))][c(T, F)][]
sort(sapply(df3[ht_cols], max), decreasing=T)

AHt  WHt DBHt  HHt  EHt  LHt 
31.5 24.5 10.0  8.2  5.3  1.3

In [119]:
#Our goal is to find an area with less percent of total covering
#At first we should delete numbers from Site area 

df3$site_name <- str_replace(df3$Site, "[:digit:]+", '')
tapply(df3$percent_covering, df3$site_name, mean)

BunkerHill      CreteCreek     HortonCreek LivingstonCreek     McAdamCreek 
       9.235714       10.021053       10.176259        9.479310        8.626316

In [132]:
ht_cols <- names(df1)[-c(1:3, ncol(df3))][c(T, F)][]
sort(sapply(df1[ht_cols], max), decreasing=T)

AHt  WHt  VOR DBHt  HHt  EHt  LHt 
31.5 24.5 19.0 10.0  8.2  5.3  1.3

In [142]:
df1[df1$DBHt == 10,]

Site           Observer Subpoint VOR PDB DBHt PW WHt PE EHt PA AHt PH HHt
518 HortonCreek121 RA       1        0   2   10   6  12  2  4.9 0  0   2  6  
    PL LHt PB
518 0  0   0

# Strings

## paste, paste0

In [402]:
paste(c("red", "blue", "green"), "ball")
paste(c("red", "blue", "green"), "ball", sep='_')
paste(c("red", "blue"), "ball", collapse=' and also ')

[1] "red ball"   "blue ball"  "green ball"

[1] "red_ball"   "blue_ball"  "green_ball"

[1] "red ball and also blue ball"

In [401]:
length("Аэрофотосъёмка ландшафта уже выявила земли богачей и процветающих крестьян.")

[1] 1

## strsplit

In [408]:
#returns list 
s <- c('one and two and three and four')
strsplit(s, ' and', fixed=T) #by default fixed = False, means that we can use Regular Expression

[[1]]
[1] "one"    " two"   " three" " four"

# grep, grepl

In [8]:
l <- c("one and two", "two and three", "four", "five", "six and seven")
l
grep("and", l) #indicates indicies with value

[1] "one and two"   "two and three" "four"          "five"         
[5] "six and seven"

[1] 1 2 5

In [ ]:
grepl("and", l) #returns logical if it contains expression

In [424]:
gsub("and", "&", l) #changes the value

[1] "one & two"   "two & three" "four"        "five"        "six & seven"

In [6]:
library(stringr) #package for convenient work with strings, all functions are vectorized and consistent

In [9]:
str_replace(l, "and", "&")

[1] "one & two"   "two & three" "four"        "five"        "six & seven"

In [12]:
str_extract(l, "tw.")

[1] "two" "two" NA    NA    NA

In [16]:
str_extract_all(l, "o*") #searching all 

[[1]]
 [1] "o" ""  ""  ""  ""  ""  ""  ""  ""  ""  "o" "" 

[[2]]
 [1] ""  ""  "o" ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "" 

[[3]]
[1] ""  "o" ""  ""  "" 

[[4]]
[1] "" "" "" "" ""

[[5]]
 [1] "" "" "" "" "" "" "" "" "" "" "" "" "" ""

# tolower,  toupper

In [17]:
tolower(month.name)

[1] "january"   "february"  "march"     "april"     "may"       "june"     
 [7] "july"      "august"    "september" "october"   "november"  "december"

In [18]:
toupper(month.abb)

[1] "JAN" "FEB" "MAR" "APR" "MAY" "JUN" "JUL" "AUG" "SEP" "OCT" "NOV" "DEC"

# Formating 

In [23]:
c(pi, exp(pi))

[1]  3.141593 23.140693

In [25]:
formatC(c(pi, exp(pi)), digits=3)

[1] "3.14" "23.1"

In [26]:
formatC(c(pi, exp(pi)), digits=3, format='e')

[1] "3.142e+00" "2.314e+01"

# Cat

In [27]:
#This is function to print objects as they are

print('You can "print" like this')
cat('You can "print" like this')

[1] "You can \"print\" like this"
You can "print" like this

In [30]:
print("One\tTwo\nThree")
cat("One\tTwo\nThree")

[1] "One\tTwo\nThree"
One	Two
Three

In [31]:
library(stringr)

hamlet <- "To be, or not to be: that is the question:
Whether 'tis nobler in the mind to suffer
The slings and arrows of outrageous fortune,
Or to take arms against a sea of troubles,
And by opposing end them?"

hamlet <- str_replace_all(hamlet, "[:punct:]", "")
hamlet <- tolower(unlist(str_split(hamlet, "[:space:]")))

In [32]:
hamlet

[1] "to"         "be"         "or"         "not"        "to"        
 [6] "be"         "that"       "is"         "the"        "question"  
[11] "whether"    "tis"        "nobler"     "in"         "the"       
[16] "mind"       "to"         "suffer"     "the"        "slings"    
[21] "and"        "arrows"     "of"         "outrageous" "fortune"   
[26] "or"         "to"         "take"       "arms"       "against"   
[31] "a"          "sea"        "of"         "troubles"   "and"       
[36] "by"         "opposing"   "end"        "them"

In [51]:
# Amount "to"
sum(str_count(hamlet, 'to'))
# Amount any words containing any of "f", "q" or "w"
sum(str_count(hamlet, "[fqw]"))
# Amount any words containing 'b' + any symbol 
sum(str_count(hamlet, "b."))
# Amount words from 7 letters
sum(str_length(hamlet)==7)

[1] 4

[1] 8

[1] 5

[1] 3

# Factor

In [64]:
f <- factor(sample(LETTERS, 30, replace=T))
f

[1] L O E A Z X B Z B D U R S W W W F P H F J D P R I P X W M K
Levels: A B D E F H I J K L M O P R S U W X Z

In [65]:
as.numeric(f)

[1] 10 12  4  1 19 18  2 19  2  3 16 14 15 17 17 17  5 13  6  5  8  3 13 14  7
[26] 13 18 17 11  9

In [66]:
as.character(f)

[1] "L" "O" "E" "A" "Z" "X" "B" "Z" "B" "D" "U" "R" "S" "W" "W" "W" "F" "P" "H"
[20] "F" "J" "D" "P" "R" "I" "P" "X" "W" "M" "K"

In [67]:
levels(f) #all unique values of factor

[1] "A" "B" "D" "E" "F" "H" "I" "J" "K" "L" "M" "O" "P" "R" "S" "U" "W" "X" "Z"

In [68]:
nlevels(f) #number of levels in factor

[1] 19

## Indexing of factor

In [69]:
f[f == 'A'] <- 'D'

In [71]:
(f <- droplevels(f))

[1] L O E D Z X B Z B D U R S W W W F P H F J D P R I P X W M K
Levels: B D E F H I J K L M O P R S U W X Z

In [73]:
levels(f) <- tolower(levels(f))
f

[1] l o e d z x b z b d u r s w w w f p h f j d p r i p x w m k
Levels: b d e f h i j k l m o p r s u w x z

In [75]:
levels(f)[1] <- 'lll'
f

[1] l   o   e   d   z   x   lll z   lll d   u   r   s   w   w   w   f   p   h  
[20] f   j   d   p   r   i   p   x   w   m   k  
Levels: lll d e f h i j k l m o p r s u w x z

In [77]:
temp <- c("freezing cold", "cold", "comfortable", "warm", "hot", "burning hot")
ft <- ordered(sample(temp, 14, replace=T), temp)
ft

[1] freezing cold burning hot   cold          hot           cold         
 [6] warm          cold          burning hot   comfortable   burning hot  
[11] warm          hot           warm          comfortable  
Levels: freezing cold < cold < comfortable < warm < hot < burning hot

In [78]:
ft[ft >= "hot"]

[1] burning hot hot         burning hot burning hot hot        
Levels: freezing cold < cold < comfortable < warm < hot < burning hot

# Cut

In [79]:
cut(rnorm(10), -5:5)

[1] (-2,-1] (-1,0]  (-2,-1] (0,1]   (1,2]   (-4,-3] (2,3]   (0,1]   (0,1]  
[10] (0,1]  
10 Levels: (-5,-4] (-4,-3] (-3,-2] (-2,-1] (-1,0] (0,1] (1,2] (2,3] ... (4,5]

In [80]:
table(cut(rnorm(1000), -5:5))


(-5,-4] (-4,-3] (-3,-2] (-2,-1]  (-1,0]   (0,1]   (1,2]   (2,3]   (3,4]   (4,5] 
      0       2      17     132     363     344     118      22       2       0 

In [83]:
options(stringsAsFactors = F) #if we don't want to have all strings as factors

# Tapply

In [84]:
str(warpbreaks) 

'data.frame':	54 obs. of  3 variables:
 $ breaks : num  26 30 54 25 70 52 51 26 67 18 ...
 $ wool   : Factor w/ 2 levels "A","B": 1 1 1 1 1 1 1 1 1 1 ...
 $ tension: Factor w/ 3 levels "L","M","H": 1 1 1 1 1 1 1 1 1 2 ...


In [88]:
tapply(warpbreaks$breaks, warpbreaks$wool, mean) #Apply function for factors
tapply(warpbreaks$breaks, warpbreaks$wool, max)

A        B 
31.03704 25.25926

A  B 
70 44

In [89]:
str(quakes)

'data.frame':	1000 obs. of  5 variables:
 $ lat     : num  -20.4 -20.6 -26 -18 -20.4 ...
 $ long    : num  182 181 184 182 182 ...
 $ depth   : int  562 650 42 626 649 195 82 194 211 622 ...
 $ mag     : num  4.8 4.2 5.4 4.1 4 4 4.8 4.4 4.7 4.3 ...
 $ stations: int  41 15 43 19 11 12 43 15 35 19 ...


In [90]:
min(quakes$mag)
max(quakes$mag)

[1] 4

[1] 6.4

In [104]:
table(cut(quakes$mag, breaks=c(4,4.5,5,5.5,6, 6.5), include.lowest=T, right=F ))


[4,4.5) [4.5,5) [5,5.5) [5.5,6) [6,6.5] 
    377     425     160      33       5 

# Functions

In [143]:
str(c(mean, min, max))

List of 3
 $ :function (x, ...)  
 $ :function (..., na.rm = FALSE)  
 $ :function (..., na.rm = FALSE)  


In [144]:
fun_list <- c(mean, min, max)

In [145]:
sapply(fun_list, function(x) x(1:1000))

[1]  500.5    1.0 1000.0

In [147]:
apply_f <- function(f, x) f(x)
sapply(fun_list, apply_f, x=1:1000)

[1]  500.5    1.0 1000.0

In [148]:
apply_f(function(x) sum(x^2), 1:10)

[1] 385

## Function as return function

In [152]:
square <- function() function(x) x^2
square()

function(x) x^2
<environment: 0x7fce3f6d5710>

In [153]:
square()(5)

[1] 25

# Binary operators

In [154]:
# x %in% y checks if y contains x

1:5 %in% c(1,3,5)

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [155]:
"%nin%" <- function(x,y) !(x%in%y)
1:5 %nin% c(1,3,5)

[1] FALSE  TRUE FALSE  TRUE FALSE

In [191]:
decorate_string <- function(pattern, string, string1, sep='', collapse=NULL) { 
      s <- paste(pattern, string, sep=sep, collapse=collapse)
      #s1 <- paste(s, stri_reverse(pattern), sep=sep, collapse=collapse)
      return(s1)
}

In [229]:
paste_all <- function(x,...) paste(x, ...)


decorate_string <- function(pattern, string, ..., sep=' ', collapse=NULL) { 
      text <- paste_all(string, ..., sep=sep, collapse=collapse)
      rev_dec <- stri_reverse(pattern)
      return(paste0(pattern, text, rev_dec))
}
                                                   

In [232]:
decorate_string <- function(pattern, ...) {
    paste0(pattern, paste(...), stri_reverse(pattern))
}

In [233]:
decorate_string(pattern = "123", "abc")            # "123abc321"
decorate_string(pattern = "123", "abc", "def")     # "123abc def321"
decorate_string(pattern = "123", c("abc", "def"))  # "123abc321" "123def321" (вектор длины 2)

decorate_string(pattern = "123", "abc", "def", sep = "+")    # "123abc+def321"
decorate_string(pattern = "!", c("x", "x"), collapse = "_")  # "!x_x!"
decorate_string(pattern = ".:", 1:2, 3:4, 5:6, sep = "&")    # ".:1&3&5:." ".:2&4&6:." (вектор длины 2)

[1] "123abc321"

[1] "123abc def321"

[1] "123abc321" "123def321"

[1] "123abc+def321"

[1] "!x_x!"

[1] ".:1&3&5:." ".:2&4&6:."

# Generator of cards

In [236]:
#Generate Deck Cards

values <- c(2:10, "Jack", "Queen", "King", "Ace")
suits <- c("Clubs", "Diamonds", "Hearts", "Spades")
card_deck <- outer(values, suits, paste, sep='_of_')

#Function_factory

generator <- function(set) function(n) sample(set, n, replace=T)
    
#Define_Generators
    
card_generator <- generator(card_deck)
coin_generator <- generator(c("Heads", "Tails"))

#Let's play

card_generator(15)
coin_generator(3)

[1] "2_of_Diamonds"  "6_of_Hearts"    "4_of_Clubs"     "3_of_Clubs"    
 [5] "6_of_Spades"    "3_of_Hearts"    "2_of_Diamonds"  "3_of_Clubs"    
 [9] "Jack_of_Spades" "10_of_Diamonds" "8_of_Diamonds"  "Ace_of_Hearts" 
[13] "5_of_Spades"    "Ace_of_Hearts"  "7_of_Clubs"

[1] "Tails" "Heads" "Heads"

In [289]:
generator <- function(set, prob = rep(1/length(set), length(set))) { 
             function(n) sample(set, n, replace=T)
} 

roulette_values <- c("Zero!", 1:36)
fair_roulette <- generator(roulette_values)
#rigged_roulette <- generator(<???>)

In [290]:
fair_roulette(1)

[1] "14"

In [280]:
#Binary operator for 2 vectors 

In [277]:
"%+%" <- function(x, y) {
    summa <- c()
    one_value <- min(length(x), length(y))
    summa[1:one_value] <- x[1:one_value] + y[1:one_value]
    length(summa) <- max(length(x), length(y))
    return(summa)
}

In [279]:
'%+%' <- function(x, y) {
    length(x) <- length(y) <- max(length(x), length(y))
    x + y
}

In [ ]:
1:5 %+% 1:2   # c(2, 4, NA, NA, NA)
5 %+% c(2, 6) # c(7, NA) 

# Object Oriented Proframming

## Replicate

In [291]:
get_status <- function(n, p=0.1) {
    x <- rbinom(n, 1, p)
    sum(x)
}
replicate(5, get_status(100))

[1] 10 12 13 10  7

## Mapply

In [293]:
mapply(seq, from = 1:4, to = 2:5, by= 1/ (1 + 1:4))

[[1]]
[1] 1.0 1.5 2.0

[[2]]
[1] 2.000000 2.333333 2.666667 3.000000

[[3]]
[1] 3.00 3.25 3.50 3.75 4.00

[[4]]
[1] 4.0 4.2 4.4 4.6 4.8 5.0

## Outer

In [297]:
dim(outer(letters, LETTERS, paste0))
head(outer(letters, LETTERS, paste0), 5)
diag(outer(letters, LETTERS, paste0))

[1] 26 26

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] aA   aB   aC   aD   aE   aF   aG   aH   aI   aJ    ...   aQ    aR    aS   
[2,] bA   bB   bC   bD   bE   bF   bG   bH   bI   bJ    ...   bQ    bR    bS   
[3,] cA   cB   cC   cD   cE   cF   cG   cH   cI   cJ    ...   cQ    cR    cS   
[4,] dA   dB   dC   dD   dE   dF   dG   dH   dI   dJ    ...   dQ    dR    dS   
[5,] eA   eB   eC   eD   eE   eF   eG   eH   eI   eJ    ...   eQ    eR    eS   
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] aT    aU    aV    aW    aX    aY    aZ   
[2,] bT    bU    bV    bW    bX    bY    bZ   
[3,] cT    cU    cV    cW    cX    cY    cZ   
[4,] dT    dU    dV    dW    dX    dY    dZ   
[5,] eT    eU    eV    eW    eX    eY    eZ

[1] "aA" "bB" "cC" "dD" "eE" "fF" "gG" "hH" "iI" "jJ" "kK" "lL" "mM" "nN" "oO"
[16] "pP" "qQ" "rR" "sS" "tT" "uU" "vV" "wW" "xX" "yY" "zZ"

## Vectorize

In [301]:
lp_norm <- function(x, p=2) {
    if (p >= 1) sum(abs(x)^p*(1/p)) else NaN
}
lp_norm(1:10, -1:4)

Warning message in if (p >= 1) sum(abs(x)^p * (1/p)) else NaN:
“the condition has length > 1 and only the first element will be used”

[1] NaN

In [302]:
lp_norm <- Vectorize(lp_norm, "p")
lp_norm(1:10, -1:4)

[1]      NaN      NaN   55.000  192.500 1008.333 6333.250

## do.call

In [306]:
df1 <- data.frame(id=1:2, value=rnorm(2))
df2 <- data.frame(id=3:4, value=runif(2))
df3 <- data.frame(id=222, value=7)
do.call(rbind, list(df1, df2, df3))

id  value      
1   1 -0.42675922
2   2 -0.06956898
3   3  0.28171133
4   4  0.95196248
5 222  7.00000000

In [ ]:
#Mulpiply use of outer function

In [333]:
cat_temper <- c("bully", "playful", "calm", "lazy")
cat_color <- c("white", "grey", "black", "redhead")
cat_age <- c("cat", "kitten")
cat_trait <- c("with smart eyes", "with sharp fingernails", "with long whiskers")


In [334]:
cats <- sort(outer(cat_temper, outer(cat_color, outer(cat_age, cat_trait, paste), paste), paste))

In [336]:
cats[1:10]

[1] "bully black cat with long whiskers"       
 [2] "bully black cat with sharp fingernails"   
 [3] "bully black cat with smart eyes"          
 [4] "bully black kitten with long whiskers"    
 [5] "bully black kitten with sharp fingernails"
 [6] "bully black kitten with smart eyes"       
 [7] "bully grey cat with long whiskers"        
 [8] "bully grey cat with sharp fingernails"    
 [9] "bully grey cat with smart eyes"           
[10] "bully grey kitten with long whiskers"

In [350]:
# Random walk with absorption
simulate_walk <- function(lower = -10, upper = 10, n_max = 200, p = 1e-3) {
  current_position <- (lower + upper) / 2
  for (i in 1:n_max) {
    is_absorbed <- rbinom(1, 1, p)
    if (is_absorbed) return(list(status = "Absorbed", 
                                 position = current_position, 
                                 steps = i))
    current_position <- current_position + rnorm(1)
    if (current_position < lower) return(list(status = "Left breach", 
                                              position = current_position, 
                                              steps = i))
    if (current_position > upper) return(list(status = "Right breach", 
                                              position = current_position, 
                                              steps = i))
  }
  return(list(status = "Max steps reached", 
              position = current_position,
              steps = n_max))
}

# Simulate results
result <- replicate(1000, simulate_walk(), simplify = FALSE)
result <- data.frame(
  status = sapply(result, function(x) x$status),
  position = sapply(result, function(x) x$position),
  steps = sapply(result, function(x) x$steps)
)

# Inspect results
tapply(result$position, result$status, length)
tapply(result$steps, result$status, mean)


Absorbed       Left breach Max steps reached      Right breach 
              100               396               102               402

Absorbed       Left breach Max steps reached      Right breach 
         65.92000          79.42172         200.00000          82.03731

In [373]:
# Random walk with absorption
simulate_walk_2d <- function(circle_r = 6, n_max = 100, p = 1e-2) {
  current_position_x <- 0
  current_position_y <- 0
  for (i in 1:n_max) {
    is_absorbed <- rbinom(1, 1, p)
    if (is_absorbed) return(list(status = "Absorbed", 
                                 position_x = current_position_x,
                                 position_y = current_position_y,
                                 steps = i))
    current_position_x <- current_position_x + rnorm(1)
    current_position_y <- current_position_y + rnorm(1)  
    current_position <- sqrt(current_position_x^2 + current_position_y^2)
    if (current_position > circle_r) return(list(status = "Out", 
                                              position_x = current_position_x,
                                              position_y = current_position_y, 
                                              steps = i))
  }
  return(list(status = "Max steps reached", 
              position_x = current_position_x,
              position_y = current_position_y,
              steps = n_max))
}


In [374]:
# Simulate results
result <- replicate(100000, simulate_walk_2d(), simplify = FALSE)
result <- data.frame(
  status = sapply(result, function(x) x$status),
  steps = sapply(result, function(x) x$steps),
  position_x = sapply(result, function(x) x$position_x),
  position_y = sapply(result, function(x) x$position_y)  
)


In [375]:
# Inspect results
tapply(result$position_x, result$status, length)
tapply(result$steps, result$status, mean)

Absorbed Max steps reached               Out 
            18874                84             81042

Absorbed Max steps reached               Out 
         14.74181         100.00000          19.77054

In [378]:
f <- function(y) {
  y <- x + y
  y
}

g <- function(x) {
  y <- f(x)
  f <- function(x) {
    y - x
  }
  y - f(x)
}

x <- 10
y <- 1
f(x); f(y)
g(x); g(y)
x; y

[1] 20

[1] 11

[1] 10

[1] 1

[1] 10

[1] 1

In [382]:
library(microbenchmark)

In [386]:
m1 <- function(x, y) {
  m <- matrix(0, length(x), length(y))
  for (i in 1:length(x)) 
    for (j in 1:length(y)) {
      m[i, j] = x[i] * y[j]
    }
  m
}

m2 <- function(x, y) {
  vapply(y, function(i) i * x, numeric(length(x)))
}

m3 <- function(x, y) x %o% y

x <- rnorm(100)
y <- runif(1000)
all.equal(m1(x, y), m2(x, y))
all.equal(m2(x, y), m3(x, y))

time <- microbenchmark(m1(x, y), m2(x, y), m3(x, y))


[1] TRUE

[1] TRUE

In [402]:
by(time$time, time$expr, mean)

time$expr: m1(x, y)
[1] 10542327
------------------------------------------------------------ 
time$expr: m2(x, y)
[1] 774555.7
------------------------------------------------------------ 
time$expr: m3(x, y)
[1] 173339.4

In [403]:
library(tidyr)

# Tidy Data

In [410]:
df <- data.frame(Name = c("John", "Peter", "Mary", "Caroline"),
                 DrugA_T1 = runif(4, 35, 36),
                 DrugA_T2 = runif(4, 36, 39),
                 DrugB_T1 = runif(4, 36, 36.6),
                 DrugB_T2 = runif(4, 37, 38.5)
); df

Name     DrugA_T1 DrugA_T2 DrugB_T1 DrugB_T2
1 John     35.78241 37.79680 36.47775 37.12533
2 Peter    35.81837 36.44466 36.51250 38.20866
3 Mary     35.99955 36.52794 36.10436 37.55310
4 Caroline 35.38916 36.01392 36.53237 37.67275

## Gather - spread (opp. of gather)

In [406]:
#From "wide" to "long" format

head(gather(df, Variable, Temperature, -Name), 6)

Name     Variable Temperature
1 John     DrugA_T1 35.19012   
2 Peter    DrugA_T1 35.70201   
3 Mary     DrugA_T1 35.32933   
4 Caroline DrugA_T1 35.87959   
5 John     DrugA_T2 38.44546   
6 Peter    DrugA_T2 36.00456

## Separate - unite (opp.of sepparate)

In [411]:
df <- gather(df, Variable, Temperature, -Name)
df <- separate(df, Variable, c("DrugType", "Time"), "_")
head(df, 8)

Name     DrugType Time Temperature
1 John     DrugA    T1   35.78241   
2 Peter    DrugA    T1   35.81837   
3 Mary     DrugA    T1   35.99955   
4 Caroline DrugA    T1   35.38916   
5 John     DrugA    T2   37.79680   
6 Peter    DrugA    T2   36.44466   
7 Mary     DrugA    T2   36.52794   
8 Caroline DrugA    T2   36.01392

# Dplyr

In [419]:
library(dplyr)


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



## Select

In [447]:
df <- data.frame(first_name = c("John", "Peter", "Mary", "Caroline"),
                 last_name = c("Gray", "Stevens", "Brown", "Hulett"),
                 email_address = c("gray@gmail.com", "stev@gmail.com", "brown@gmail.com", "hul@gmail.com"),
                 postal_address = c(90100, 90106, 20100, 90170),
                 date_added = c("24.04.21", "24.04.21","22.08.21", "20.08.22"),
                 sales = c(5, 6, 7, 8)
); df

first_name last_name email_address   postal_address date_added sales
1 John       Gray      gray@gmail.com  90100          24.04.21   5    
2 Peter      Stevens   stev@gmail.com  90106          24.04.21   6    
3 Mary       Brown     brown@gmail.com 20100          22.08.21   7    
4 Caroline   Hulett    hul@gmail.com   90170          20.08.22   8

In [433]:
select(df, first_name, last_name, date_added) #to choose from df by columns
#Same will be
#select(df, contains("name"), date_added)
#select(df, -(contains("address")))
#select(df, matches("_.{4,5}$"))
#df %>% select(c(1:2, 5))

first_name last_name date_added
1 John       Gray      24.04.21  
2 Peter      Stevens   24.05.21  
3 Mary       Brown     22.08.21  
4 Caroline   Hulett    20.08.22

In [434]:
select(df, starts_with("f"))

first_name
1 John      
2 Peter     
3 Mary      
4 Caroline

# Filter

In [439]:
filter(df, postal_address == 90100, first_name %in% c("John", "Peter")) #to choose from df rows

first_name last_name email_address  postal_address date_added
1 John       Gray      gray@gmail.com 90100          24.04.21

# Arrange 

In [441]:
#to sort our df by several arguments

arrange(df, last_name, first_name, -postal_address)

first_name last_name email_address   postal_address date_added
1 Mary       Brown     brown@gmail.com 20100          22.08.21  
2 John       Gray      gray@gmail.com  90100          24.04.21  
3 Caroline   Hulett    hul@gmail.com   90170          20.08.22  
4 Peter      Stevens   stev@gmail.com  90106          24.05.21

# Mutate

In [443]:
#function to make new or change values

mutate(df, email_address = gsub("gmail.com", "yahoo.com", email_address))

first_name last_name email_address   postal_address date_added
1 John       Gray      gray@yahoo.com  90100          24.04.21  
2 Peter      Stevens   stev@yahoo.com  90106          24.05.21  
3 Mary       Brown     brown@yahoo.com 20100          22.08.21  
4 Caroline   Hulett    hul@yahoo.com   90170          20.08.22

# Group_by and summarize

In [449]:
summarize(group_by(df, date_added),
         Avgmean = mean(sales))

date_added Avgmean
1 20.08.22   8.0    
2 22.08.21   7.0    
3 24.04.21   5.5

# Operator %>% (pipes)

In [452]:
df <- data.frame(type = c(1, 1, 2, 2, 3, 3), value = c(5, 10, 50, 100, 7, 7))
df

type value
1 1      5  
2 1     10  
3 2     50  
4 2    100  
5 3      7  
6 3      7

In [459]:
# we need to group by our data by type and count the total value for each type and then sort it by total 
#1
arrange(
  summarise(
    group_by(df, type), 
    total = sum(value)
  ),
  total
)

type total
1 3     14  
2 1     15  
3 2    150

In [456]:
#2
a <- group_by(df, type)
b <- summarise(a, total = sum(value))
c <- arrange(b, total)
c

type total
1 3     14  
2 1     15  
3 2    150

In [458]:
#3
df %>%
  group_by(type) %>%
  summarise(total = sum(value)) %>%
  arrange(total)

type total
1 3     14  
2 1     15  
3 2    150

In [464]:
avian <- read.csv('https://raw.githubusercontent.com/tonytonov/Rcourse/master/R%20programming/avianHabitat.csv')
head(avian, 5)

Site         Observer Subpoint VOR PDB DBHt PW WHt PE EHt PA AHt PH HHt PL
1 BunkerHill27 RA       1        6.0 3   5.2  0  0.0 4  2.9 0  0   4  3.0 0 
2 BunkerHill27 RA       2        4.5 2   3.1  3  4.7 3  4.1 0  0   3  3.5 2 
3 BunkerHill27 RA       3        2.0 4   5.5  1  5.8 3  3.9 0  0   3  7.5 0 
4 BunkerHill27 RA       4        2.5 3   6.2  0  0.0 3  4.0 0  0   4  5.0 0 
5 BunkerHill27 RA       5        4.0 4   5.4  0  0.0 3  3.5 0  0   4  3.7 0 
  LHt PB
1 0   0 
2 1   0 
3 0   0 
4 0   0 
5 0   0

In [463]:
avian %>% 
  filter(PDB > 0, DBHt > 0) %>% 
  select(Site, Observer, contains("DB")) %>% 
  mutate(Site = factor(str_replace(Site, "[:digit:]+", ""))) %>% 
  group_by(Site, Observer) %>% 
  summarise(MaxHt = max(DBHt)) %>% 
  filter(MaxHt >= 5) 

Site        Observer MaxHt
1 BunkerHill  JT        9.9 
2 BunkerHill  RA        7.0 
3 HortonCreek RA       10.0 
4 McAdamCreek RA        7.2 
5 McAdamCreek RR        5.0